FROM ubuntu:18.04

# install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    sudo \
    ca-certificates \
    libgtk2.0-0 \
    libcanberra-gtk-module \
    bzip2 \
    libx11-6 \
   	libxxf86vm1 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user and switch to it. Running X11 applications as root does
# not always work.
RUN adduser --disabled-password --gecos '' --shell /bin/bash user
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user

USER user
WORKDIR /home/user

# Install Miniconda
RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# Install OpenCV3 Python bindings
RUN conda install -y -c menpo opencv3=3.1.0
RUN conda clean -ya

RUN conda install -c anaconda wxpython

RUN pip install transformations

# -----------------------------------------------------------------------------
# Additional installs so that Spyder can connect to the remote kernel and can 
# view Matplotlib results.
RUN pip install IPython==5.0 \
  ipykernel==4.10 matplotlib spyder-kernels

# TODO: fix this.
RUN pip install --upgrade pip
RUN pip uninstall tornado --yes
RUN pip install tornado

RUN sudo apt-get update && sudo apt-get install -y \
    libgl1-mesa-glx \
    libqt5x11extras5 \
 && sudo rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/user/.local/share/jupyter/runtime/remote_keypointgui_kernels
# -----------------------------------------------------------------------------
