FROM ubuntu:18.04
WORKDIR /root

# install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    ca-certificates \
    libgtk2.0-0 \
    libcanberra-gtk-module \
    bzip2 \
    libx11-6 \
   	libxxf86vm1 \
    && rm -rf /var/lib/apt/lists/*

# Install Miniconda
RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV PATH=/root/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# Install OpenCV3 Python bindings
RUN conda install -y -c menpo opencv3=3.1.0 \
    && conda clean -ya

RUN conda install -c anaconda wxpython
